ALTER TABLE "Venta"
ADD COLUMN "tipo" TEXT NOT NULL DEFAULT 'Venta',
ADD COLUMN "concepto" TEXT,
ADD COLUMN "pedidoId" INTEGER;

ALTER TABLE "Pedido"
ADD COLUMN "anticipo" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "metodoAnticipo" TEXT,
ADD COLUMN "anticipoVentaId" INTEGER,
ADD COLUMN "entregaVentaId" INTEGER;
